#!/bin/sh

#################################################################################
#
# Databases
#
#################################################################################
#
    # Status of database processes
    MYSQL_RUNNING=0
    # Paths to DATADIR
    sMYSQLDBPATHS="/var/lib/mysql"
    # Paths to my.cnf
    sMYCNFLOCS="/etc/mysql/my.cnf /usr/etc/my.cnf"
#
#################################################################################
#
    InsertSection "Databases"
    
    # Test        : DBS-1804
    # Description : Check if MySQL is being used
    Register --test-no DBS-1804 --weight L --network NO --description "Checking active MySQL process"
    if [ ${SKIPTEST} -eq 0 ]; then
	FIND=`${PSBINARY} ax | egrep "mysqld|mysqld_safe" | grep -v "grep"`
	if [ "${FIND}" = "" ]; then
	    Display --indent 2 --text "- MySQL process status..." --result "NOT FOUND" --color WHITE
	    logtext "Result: MySQL process not active"
	  else
	    Display --indent 2 --text "- MySQL process status..." --result "FOUND" --color GREEN
	    logtext "Result: MySQL is active"
	    MYSQL_RUNNING=1
	fi
    fi
#
#################################################################################
#
    # Test        : DBS-1816
    # Description : Check empty MySQL root password
    # Notes       : Only perform test when MySQL is running and client is available
    if [ ! "${MYSQLCLIENTBINARY}" = "" -a ${MYSQL_RUNNING} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no DBS-1816 --preqs-met ${PREQS_MET} --weight L --network NO --description "Checking MySQL root password"
    if [ ${SKIPTEST} -eq 0 ]; then
	logtext "Test: Trying to login to local MySQL server without password"
	FIND=`${MYSQLCLIENTBINARY} -u root --password= --silent --batch --execute="" 2> /dev/null; echo $?`
	if [ "${FIND}" = "0" ]; then
	    logtext "Result: Login succeeded, no MySQL root password set!"
	    ReportWarning ${TEST_NO} "H" "No MySQL root password set"
	    ReportSuggestion ${TEST_NO} "Use mysqladmin to set a MySQL root password (mysqladmin -u root -p password MYPASSWORD)"
	    Display --indent 4 --text "- Checking empty MySQL root password" --result WARNING --color RED
	    AddHP 0 2
	  else
	    logtext "Result: Login did not succeed, so a MySQL root password is set"	    
	    Display --indent 4 --text "- Checking MySQL root password" --result OK --color GREEN
	    AddHP 2 2
	fi
      else
        logtext "Test skipped, MySQL daemon not running or no MySQL client available"
    fi
#
wait_for_keypress

#
#================================================================================
